costs_order_path = r'docs/Приказ_о_стоимости_обучения_аспирантов_на_2024_2025_учебный_год.pdf'
military_order_path = r'docs/Приказ_Об_организации_воинского_учета_граждан,_в_т_ч_бронировнаия.PDF'
students_list_path = r'docs/Списки аспирантов.xlsx'
existing_notification_path = r'data/existing_notification.csv'
db_path = r'data/users.db'